version: '3.8'

services:
  web:
    build: .
    ports:
      - "5130:5130"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./olimpia.db:/data/olimpia.db
